version: '3'

services:
  database:
    image: mongo:3.6
    ports:
      - 27017:27017
    networks:
      - internal
  server:
    build: .
    ports:
      - 8080:8080
    working_dir: /app
    command: npm run docker
    networks:
      - internal
    environment:
      - DBHOST=database
      - PORT=8080
networks:
  internal: