export const API_CALL = Symbol('CALL_API');

export const WIZARD_FILES_COUNTER_INCREMENT = 'WIZARD_FILES_COUNTER_INCREMENT';
export const WIZARD_FILES_LIST_ADD = 'WIZARD_FILES_LIST_ADD';

export const AUTH_USER_PENDING = 'AUTH_USER_PENDING';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_ERROR ='AUTH_USER_ERROR';
export const UNAUTH_USER = 'UNAUTH_USER';

export const RECORDS_SAVE_RECORD = 'RECORDS_SAVE_RECORD';
export const RECORDS_FETCH_USER_RECORDS = 'RECORDS_FETCH_USER_RECORDS';
export const RECORD_FETCH = 'RECORD_FETCH';

export const RECORDS_USER_RECORDS_PENDING = 'RECORDS_USER_RECORDS_PENDING';
export const RECORDS_USER_RECORDS_SUCCESS = 'RECORDS_USER_RECORDS_SUCCESS';
export const RECORDS_USER_RECORDS_ERROR = 'RECORDS_USER_RECORDS_ERROR';

export const RECORD_CREATE_RECORD_PENDING = 'RECORD_CREATE_RECORD_PENDING';
export const RECORD_CREATE_RECORD_SUCCESS = 'RECORD_CREATE_RECORD_SUCCESS';
export const RECORD_CREATE_RECORD_ERROR = 'RECORD_CREATE_RECORD_ERROR';
