export const API_CALL = Symbol('CALL_API');

export const WIZARD_FILES_COUNTER_INCREMENT = 'WIZARD_FILES_COUNTER_INCREMENT';
export const WIZARD_FILES_LIST_ADD = 'WIZARD_FILES_LIST_ADD';

export const AUTH_USER_PENDING = 'AUTH_USER_PENDING';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_ERROR ='AUTH_USER_ERROR';
export const UNAUTH_USER = 'UNAUTH_USER';

export const RECORDS_USER_RECORDS_PENDING = 'RECORDS_USER_RECORDS_PENDING';
export const RECORDS_USER_RECORDS_SUCCESS = 'RECORDS_USER_RECORDS_SUCCESS';
export const RECORDS_USER_RECORDS_ERROR = 'RECORDS_USER_RECORDS_ERROR';

export const RECORDS_REPORTED_RECORDS_PENDING = 'RECORDS_REPORTED_RECORDS_PENDING';
export const RECORDS_REPORTED_RECORDS_SUCCESS = 'RECORDS_REPORTED_RECORDS_SUCCESS';
export const RECORDS_REPORTED_RECORDS_ERROR = 'RECORDS_REPORTED_RECORDS_ERROR';

export const RECORD_CREATE_RECORD_PENDING = 'RECORD_CREATE_RECORD_PENDING';
export const RECORD_CREATE_RECORD_SUCCESS = 'RECORD_CREATE_RECORD_SUCCESS';
export const RECORD_CREATE_RECORD_ERROR = 'RECORD_CREATE_RECORD_ERROR';

export const RECORD_GET_RECORD_PENDING = 'RECORD_GET_RECORD_PENDING';
export const RECORD_GET_RECORD_SUCCESS = 'RECORD_GET_RECORD_SUCCESS';
export const RECORD_GET_RECORD_ERROR = 'RECORD_GET_RECORD_ERROR';

export const RECORD_REPORT_RECORD_PENDING = 'RECORD_REPORT_RECORD_PENDING';
export const RECORD_REPORT_RECORD_SUCCESS = 'RECORD_REPORT_RECORD_SUCCESS';
export const RECORD_REPORT_RECORD_ERROR = 'RECORD_REPORT_RECORD_ERROR';

export const RECORD_GET_RECORD_FILE_PENDING = 'RECORD_GET_RECORD_FILE_PENDING';
export const RECORD_GET_RECORD_FILE_SUCCESS = 'RECORD_GET_RECORD_FILE_SUCCESS';
export const RECORD_GET_RECORD_FILE_ERROR = 'RECORD_GET_RECORD_FILE_ERROR';
export const RECORD_RESET_RECORD_FILES = 'RECORD_RESET_RECORD_FILES';
